Repository grammatek/simaromur, pull requests merged in 2022-10, with the labels that each got.

#119 Make connection to github configurable
  app/src/main/assets/config.properties
  app/src/main/java/com/grammatek/simaromur/AppRepository.java
  app/src/main/java/com/grammatek/simaromur/network/remoteasset/VoiceRepo.java
  app/src/main/java/com/grammatek/simaromur/utils/FileUtils.java
Labels: enhancement, 1.2.x

#121 Generalize network api
  Readme.md
  app/build.gradle
  app/schemas/com.grammatek.simaromur.db.ApplicationDb/5.json
  app/src/main/java/com/grammatek/simaromur/ApiDbUtil.java
  app/src/main/java/com/grammatek/simaromur/AppRepository.java
  app/src/main/java/com/grammatek/simaromur/TTSObserver.java
  app/src/main/java/com/grammatek/simaromur/TTSService.java
  app/src/main/java/com/grammatek/simaromur/VoiceInfo.java
  app/src/main/java/com/grammatek/simaromur/VoiceManager.java
  app/src/main/java/com/grammatek/simaromur/VoiceViewModel.java
  app/src/main/java/com/grammatek/simaromur/db/ApplicationDb.java
  app/src/main/java/com/grammatek/simaromur/db/Voice.java
  app/src/main/java/com/grammatek/simaromur/db/VoiceDao.java
  app/src/main/java/com/grammatek/simaromur/device/TTSEngineController.java
  app/src/main/java/com/grammatek/simaromur/network/ConnectionCheck.java
  app/src/main/java/com/grammatek/simaromur/network/api/Endpoint.java
  app/src/main/java/com/grammatek/simaromur/network/api/NetworkServiceGenerator.java
  app/src/main/java/com/grammatek/simaromur/network/api/SpeakController.java
  app/src/main/java/com/grammatek/simaromur/network/api/VoiceController.java
  app/src/main/java/com/grammatek/simaromur/network/api/pojo/SpeakRequest.java
  app/src/main/java/com/grammatek/simaromur/network/api/pojo/VoiceResponse.java
  app/src/main/java/com/grammatek/simaromur/network/tiro/TiroAPI.java
  app/src/main/res/xml/network_security_config.xml
  app/src/test/java/com/grammatek/simaromur/TestRoomDbMigration.java
Labels: enhancement, 1.2.x

#120 Abn digits keyboard
  app/src/main/java/com/grammatek/simaromur/frontend/Tokenizer.java
  app/src/test/java/com/grammatek/simaromur/NormalizationManagerTest.java
Labels: bugfix, 1.3.x

#122 improved normalizing of URLs and uppercase tokens
  app/src/main/java/com/grammatek/simaromur/frontend/NormalizationDictionaries.java
  app/src/main/java/com/grammatek/simaromur/frontend/TTSNormalizer.java
  app/src/main/java/com/grammatek/simaromur/frontend/Tokenizer.java
  app/src/test/java/com/grammatek/simaromur/NormalizationManagerTest.java
Labels: 1.3.x, improvement

#123 Add more configuration settings …
  app/src/main/assets/config.properties
  app/src/main/java/com/grammatek/simaromur/TTSProcessingResult.java
  app/src/main/java/com/grammatek/simaromur/TTSService.java
Labels: technical debt, 1.3.x, improvement

#128 Abn dictionary fixes
  app/src/main/java/com/grammatek/simaromur/frontend/TupleRules.java
  app/src/main/res/raw/ice_pron_dict_standard_clear_2201_extended.csv
  app/src/main/res/raw/lexicon_v2201.txt
Labels: 1.3.x, improvement

#118 updating download voice dialog
  app/src/main/java/com/grammatek/simaromur/VoiceInfo.java
  app/src/main/java/com/grammatek/simaromur/device/DownloadVoiceManager.java
  app/src/main/java/com/grammatek/simaromur/network/remoteasset/VoiceRepo.java
  app/src/main/java/com/grammatek/simaromur/utils/AsyncThread.java
  app/src/main/java/com/grammatek/simaromur/utils/Decompress.java
  app/src/main/res/layout/activity_progress_bar.xml
  app/src/main/res/layout/activity_progress_bar_indeterminate.xml
  app/src/main/res/layout/activity_voice_info.xml
  app/src/main/res/values-is-rIS/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: bugfix, 1.3.x
